version: '3.3'
services:
  database:
    image: mysql:5.7
    container_name: mysql_auth
    restart: always
    environment:
      MYSQL_DATABASE: 'db'   
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'      
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 5
      timeout: 3s
